service: slack-sns-trigger
provider:
  name: aws
  stage: dev
  region: ap-southeast-2
  versionFunctions: false
custom:
  apiGatewayServiceProxies:
    - sqs:
        path: /sqs
        method: post
        queueName: { 'Fn::GetAtt': ['SQSQueue', 'QueueName'] }
        cors: true

resources:
  Resources:
    SQSQueue:
      Type: 'AWS::SQS::Queue'
plugins:
  - serverless-apigateway-service-proxy
